sudo: true
language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm test
- npm run coveralls
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        on:
          branch: main
        provider: script
        script:
          - npm run semantic-release